// Ledger entries (one per frozen asset) and credits (§7.8).
import { BUILTIN_FONTS, LedgerEntry } from "@docmaker/core";
import type { AssetProviderId, FrozenAsset, Lang, Ledger, LicenseInfo, MusicDoc, SfxEntry, UsageDoc, VoiceTrack } from "@docmaker/core";
import { attributionText, LICENSE_LABEL } from "./license";
import { isPipelineGenerated, licenseOfAsset } from "./validate";
import { cleanAuthor, nowIso } from "./util";

/** mm:ss (h:mm:ss above an hour); `round` = floor for range starts, ceil for range ends (the range always covers the clip). */
const tc = (ms: number, round: (x: number) => number = Math.round) => {
  const s = Math.max(0, round(ms / 1000));
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const ss = String(s % 60).padStart(2, "0");
  return h > 0 ? `${h}:${String(m).padStart(2, "0")}:${ss}` : `${String(m).padStart(2, "0")}:${ss}`;
};

/** Human-readable transformations applied by the conform recipe. */
export function transformationsOf(a: FrozenAsset): string[] {
  const out: string[] = [];
  const r = a.conform.recipe;
  if (r === "image-v1" || r === "proc-image-v1") out.push("exif-rotate", `resize long edge ≤ 2880 (${a.width}×${a.height})`, a.ext === "png" ? "png" : "jpeg q90");
  if (r.startsWith("video") || r === "proc-video-v1" || r === "clip-v1") {
    if (a.conform.sourceInMs !== null && a.conform.sourceOutMs !== null) out.push(`trim ${tc(a.conform.sourceInMs, Math.floor)}–${tc(a.conform.sourceOutMs, Math.ceil)}`);
    out.push(`transcode h264 cfr ${a.fps ?? "?"}`, a.hasAudio ? "aac 192k" : "muted");
  }
  if (r === "clip-v1" || r === "audio-norm-v1") out.push(`loudnorm ${a.lufs ?? -18} LUFS`);
  if (r.startsWith("proc-")) out.unshift("generated procedurally");
  return out;
}

export function providerOfAsset(a: FrozenAsset): AssetProviderId {
  if (a.candidate) return a.candidate.provider;
  if (a.declaration) return "local";
  return "procedural";
}

export function ledgerEntryFor(a: FrozenAsset): LedgerEntry {
  const license = licenseOfAsset(a);
  const c = a.candidate;
  const provider = providerOfAsset(a);
  const title = c?.title ?? (isPipelineGenerated(a) ? `Procedural ${a.kind} (${a.conform.recipe})` : a.declaration ? a.declaration.note || "Imported media" : "Media");
  const author = cleanAuthor(c?.author?.name ?? (a.declaration?.author || null));
  const sourcePageUrl = c?.sourcePageUrl ?? a.declaration?.url ?? "";
  const attr = license.attributionText ?? attributionText({ title, author, license, sourcePageUrl: sourcePageUrl || null });
  return LedgerEntry.parse({
    assetId: a.id, provider, title, sourcePageUrl, fileUrl: c?.downloadUrl ?? "", author, license: { ...license, attributionText: attr },
    attributionText: attr, retrievedAt: c?.retrievedAt ?? a.frozenAt ?? nowIso(), youtube: c?.youtube ?? null, declaration: a.declaration,
    transformations: transformationsOf(a),
  });
}

/** Ledger for the given assets (sorted by assetId; deterministic). */
export function buildLedger(assets: Iterable<FrozenAsset>): Ledger {
  const entries = [...assets].map(ledgerEntryFor).sort((a, b) => (a.assetId < b.assetId ? -1 : a.assetId > b.assetId ? 1 : 0));
  return { schemaVersion: 1, entries };
}

// ------------------------------------------------------------------------------------------------ credits
const T = {
  en: {
    title: "Credits", archival: "Archival & Creative Commons", stock: "Stock footage and photos", web: "Web images (editorial use)",
    clips: "Clips (quotation / fair use)", music: "Music", sfx: "Sound effects", voice: "Voice", ai: "AI-generated images (labelled on screen)",
    own: "Your own and imported media", procedural: "Procedural visuals", fonts: "Fonts", ytBlock: "YouTube description",
    procLine: "Backgrounds and textures generated procedurally by DocumentaryMaker.", procSfx: "Procedural sound effects generated by DocumentaryMaker.",
    procMusic: "Procedural music generated by DocumentaryMaker.",
    synthetic: "Reminder: this video contains altered or synthetic content (AI images and/or a synthetic voice). Disclose it when uploading (YouTube: \"Altered or synthetic content\").",
    elevenFree: "Warning: ElevenLabs free tier — non-commercial use only and attribution required.",
    syntheticVoice: "synthetic voice", recording: "recorded by the creator", modified: "cropped, colour-graded and animated",
    modifiedVideo: "trimmed and colour-graded",
    shareAlike: "ShareAlike: works marked CC BY-SA keep their licence; anyone adapting those works must share the adaptation under the same licence.",
  },
  fr: {
    title: "Crédits", archival: "Archives et Creative Commons", stock: "Vidéos et photos de stock", web: "Images web (usage éditorial)",
    clips: "Extraits (droit de citation)", music: "Musique", sfx: "Effets sonores", voice: "Voix", ai: "Images générées par IA (signalées à l'écran)",
    own: "Vos médias et imports", procedural: "Visuels procéduraux", fonts: "Polices", ytBlock: "Description YouTube",
    procLine: "Fonds et textures générés de façon procédurale par DocumentaryMaker.", procSfx: "Effets sonores procéduraux générés par DocumentaryMaker.",
    procMusic: "Musique procédurale générée par DocumentaryMaker.",
    synthetic: "Rappel : cette vidéo contient du contenu modifié ou synthétique (images IA et/ou voix de synthèse). Signalez-le lors de la mise en ligne (YouTube : « Contenu modifié ou synthétique »).",
    elevenFree: "Attention : offre gratuite ElevenLabs — usage non commercial uniquement, attribution obligatoire.",
    syntheticVoice: "voix de synthèse", recording: "enregistrée par l'auteur", modified: "recadré, étalonné et animé",
    modifiedVideo: "coupé et étalonné",
    shareAlike: "Partage dans les mêmes conditions : les œuvres sous CC BY-SA gardent leur licence ; toute adaptation de ces œuvres doit être partagée sous la même licence.",
  },
} as const;

function licText(l: LicenseInfo): string {
  return `${LICENSE_LABEL[l.code]}${l.version ? ` ${l.version}` : ""}`;
}
const isSa = (l: LicenseInfo) => l.code.endsWith("-SA") || l.restrictions.includes("sa");

/** Canonical Creative Commons URL of a licence (https, no "deed.xx", trailing slash), built from the code and version when
 *  the provider gave none; other URLs are kept as given; null when there is none. */
export function licenseUrl(l: Pick<LicenseInfo, "code" | "version" | "url">): string | null {
  const given = (l.url ?? "").trim();
  if (given !== "") {
    const m = /^https?:\/\/creativecommons\.org\/((?:licenses|publicdomain)\/[a-z-]+(?:\/\d+(?:\.\d+)?)?)/i.exec(given);
    return m ? `https://creativecommons.org/${m[1]!.toLowerCase()}/` : given;
  }
  if (l.code === "CC0") return "https://creativecommons.org/publicdomain/zero/1.0/";
  if (l.code === "PDM") return "https://creativecommons.org/publicdomain/mark/1.0/";
  if (l.code.startsWith("CC-BY") && l.version) return `https://creativecommons.org/licenses/${l.code.slice(3).toLowerCase()}/${l.version}/`;
  return null;
}

/** Kind of media a ledger entry describes, from its transformations (a transcode → video). */
const isVideoEntry = (e: { transformations?: readonly string[] }) => (e.transformations ?? []).some((t) => t.startsWith("transcode"));

/** `"<title>" by <author> — <licence> (<licence URL>) — <source> — <modified note>`: every licence with a known deed carries
 *  its link, and every visual says how it was changed (stills are cropped, colour-graded and animated; videos trimmed and
 *  colour-graded) — CC BY* licences require it, and it is honest for public-domain works too. */
function line(e: { title: string; author: string | null; license: LicenseInfo; sourcePageUrl: string; transformations?: readonly string[] }, lang: Lang, visual = true): string {
  const t = e.title.trim() || "Untitled";
  const author = cleanAuthor(e.author);
  const by = lang === "fr" ? "par" : "by";
  const url = licenseUrl(e.license);
  const lic = `${licText(e.license)}${url ? ` (${url})` : ""}`;
  const modified = visual ? ` — ${isVideoEntry(e) ? T[lang].modifiedVideo : T[lang].modified}` : "";
  return `"${t}"${author ? ` ${by} ${author}` : ""} — ${lic}${e.sourcePageUrl ? ` — ${e.sourcePageUrl}` : ""}${modified}`;
}

const ARCHIVAL = new Set<string>(["wikimedia", "loc", "internet-archive", "nasa", "openverse"]);
const STOCK = new Set<string>(["pexels", "pixabay"]);

export function buildCredits(i: { ledger: Ledger; usage: UsageDoc; lang: Lang; voice: VoiceTrack | null; music: MusicDoc; sfx: readonly SfxEntry[] }): string {
  const t = T[i.lang];
  const used = new Set(i.usage.usage.map((u) => u.assetId));
  const entries = i.ledger.entries.filter((e) => used.has(e.assetId));
  const groups: { title: string; lines: string[] }[] = [];
  const add = (title: string, lines: string[]) => {
    const uniq = [...new Set(lines)].sort((a, b) => a.localeCompare(b));
    if (uniq.length > 0) groups.push({ title, lines: uniq });
  };
  const ai = entries.filter((e) => e.license.code === "AI-GENERATED");
  const rest = entries.filter((e) => e.license.code !== "AI-GENERATED");
  const ln = (e: Ledger["entries"][number]) => line(e, i.lang, true);
  add(t.archival, rest.filter((e) => ARCHIVAL.has(e.provider)).map(ln));
  add(t.stock, rest.filter((e) => STOCK.has(e.provider)).map((e) => `${ln(e)}${e.provider === "pexels" ? " (Pexels)" : " (Pixabay)"}`));
  add(t.web, rest.filter((e) => e.provider === "brave").map(ln));
  const isClip = (e: Ledger["entries"][number]) => e.provider === "youtube" || e.youtube !== null || e.license.code === "YOUTUBE-FAIR-USE";
  add(t.clips, rest.filter(isClip).map((e) => {
    const y = e.youtube;
    const span = y && y.startMs !== null && y.endMs !== null ? ` [${tc(y.startMs, Math.floor)}–${tc(y.endMs, Math.ceil)}]` : "";
    return `"${e.title}" — ${y?.channel ?? e.author ?? "unknown channel"} — ${y?.url ?? e.sourcePageUrl}${span}`;
  }));
  // Music: tracks used by this language's timeline.
  const musicLines: string[] = [];
  for (const tr of i.music.tracks.filter((m) => used.has(m.assetId))) {
    musicLines.push(tr.source === "procedural" ? t.procMusic : line({ title: tr.title, author: null, license: tr.license, sourcePageUrl: "" }, i.lang, false));
  }
  add(t.music, musicLines);
  const sfxUsed = i.sfx.filter((s) => used.has(s.assetId));
  add(t.sfx, sfxUsed.map((s) => (s.pack === "procedural" ? t.procSfx : s.license.attributionText ?? `${s.pack}: ${s.category} — ${licText(s.license)}`)));
  // Voice (from the active take's licence).
  const voiceLines: string[] = [];
  let syntheticVoice = false;
  if (i.voice) {
    const v = i.voice;
    syntheticVoice = v.provider !== "recording";
    const kind = v.provider === "recording" ? t.recording : t.syntheticVoice;
    voiceLines.push(`${v.provider} — ${v.voiceId} (${kind}) — ${licText(v.license)}${v.license.attributionText ? ` — ${v.license.attributionText}` : ""}`);
    if (v.provider === "elevenlabs" && (v.license.restrictions.includes("nc") || !v.license.commercialOk)) voiceLines.push(t.elevenFree);
  }
  add(t.voice, voiceLines);
  add(t.ai, ai.map((e) => `${ln(e)} (AI)`));
  add(t.own, rest.filter((e) => e.provider === "local" && !isClip(e)).map((e) => (e.declaration?.kind === "own-work" ? `"${e.title}" — ${e.author ?? ""} (${LICENSE_LABEL["USER-OWNED"]})` : ln(e))));
  if (rest.some((e) => e.provider === "procedural")) add(t.procedural, [t.procLine]);
  add(t.fonts, BUILTIN_FONTS.map((f) => `${f.family} — SIL Open Font License 1.1`));

  const out: string[] = [`# ${t.title}`, ""];
  for (const g of groups) {
    out.push(`## ${g.title}`, "");
    for (const l of g.lines) out.push(`- ${l}`);
    out.push("");
  }
  // Compact block to paste into the YouTube description (no fonts, no procedural lines).
  const yt: string[] = [];
  for (const g of groups) {
    if (g.title === t.fonts || g.title === t.procedural) continue;
    for (const l of g.lines) if (l !== t.procMusic && l !== t.procSfx) yt.push(l);
  }
  out.push(`## ${t.ytBlock}`, "", "```", ...(yt.length > 0 ? yt : ["—"]), "```", "");
  if (ai.length > 0 || syntheticVoice) out.push(`> ${t.synthetic}`, "");
  if (entries.some((e) => isSa(e.license) && e.license.code.startsWith("CC-BY"))) out.push(`> ${t.shareAlike}`, "");
  return out.join("\n");
}
